
name: Create new release

on:
  push:
    branches:
      - "**"
    tags:
      - "!**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    #runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Install fuse and libfuse2
      run: sudo apt install fuse libfuse2

    - name: Get appimagetool
      run: |
        set -x
        #wget -q https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
        version_go_appimage=$(wget -q -O - https://api.github.com/repos/probonopd/go-appimage/releases | grep "\"name.*appimagetool-.*-x86_64.AppImage\"" | head -n 1 | cut -d '-' -f2)
        echo "version_go_appimage: $version_go_appimage"
        wget -q "https://github.com/probonopd/go-appimage/releases/download/continuous/appimagetool-$version_go_appimage-x86_64.AppImage" -O appimagetool-x86_64.AppImage
        chmod +x appimagetool-x86_64.AppImage
        pwd; ls -lah

    - name: Get Python AppImage
      run: |
        set -x
        #wget -q https://github.com/niess/python-appimage/releases/download/python3.12/python3.12.3-cp312-cp312-manylinux_2_28_x86_64.AppImage
        wget -q https://github.com/ryuuzaki42/Python_to_make_AppImage/releases/download/06/python3.13.3-cp313-cp313-manylinux2014_x86_64.AppImage
        fileName=$(ls python3*.AppImage)
        chmod +x "$fileName"
        ./"$fileName" --appimage-extract
        pwd; ls -lah

    - name: Install DisplayCAL and update pip
      run: |
        set -x
        cd squashfs-root/opt/python3*/bin/
        pwd; ls -lah

        ./pip3* install --upgrade pip

        #- dbus
        sudo apt update
        sudo apt install libdbus-1-dev pkg-config

        #- wxPython
        wget -q https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-20.04/wxPython-4.2.2-cp313-cp313-linux_x86_64.whl
        ./pip3 install wxPython-*.whl
        mv wxPython-*.whl ../../../../

        ./pip3 install displaycal

    - name: Make AppImage
      run: |
        set -x
        tag=1 #1
        version=$(grep -o "DisplayCAL-py3:.*" README.md | cut -d ' ' -f2)
        echo "DisplayCAL-py3 version: $version - Tag: $tag"

        cd squashfs-root/
        pwd; ls -lah
        #rm -v python.png python*.desktop .DirIcon AppRun
        rm -v .DirIcon AppRun
        mv python*.desktop DisplayCAL-py3.desktop

        #find . | grep ".png"
        #ln -s opt/python3.*/share/icons/hicolor/512x512/apps/maestral.png maestral.png

        #find . | grep ".desktop"
        #ln -s opt/python3*/share/applications/maestral.desktop DisplayCAL-py3.desktop
        cat DisplayCAL-py3.desktop
        pwd; ls -lah

        sed -i 's/=python3.13.3/=DisplayCAL-py3/g' DisplayCAL-py3.desktop

        echo '#!/bin/bash
        HERE="$(dirname "$(readlink -f "${0}")")"

        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HERE/usr/libjpeg/
        export PATH=$PATH:$HERE/ArgyllCMS/bin/

        cd "$HERE"/opt/python3*/bin/
        ./displaycal "$@"' > AppRun
        chmod +x AppRun

        ## Added libjpeg.so.8
        #find /usr/ | grep "libjpeg."
        mkdir usr/libjpeg/
        cp /usr/lib/x86_64-linux-gnu/libjpeg.so* usr/libjpeg/

        # Added ArgyllCMS
        wget -q https://www.argyllcms.com/Argyll_V3.5.0_linux_x86_64_bin.tgz
        tar -xvf Argyll_*_bin.tgz
        mv Argyll_*.0/ ArgyllCMS/
        mv Argyll_*_bin.tgz ../

        cd ../
        cp README.md squashfs-root/
        ls -lah squashfs-root/

        # Wrong permissions on AppDir, please set it to 0755 and try again
        chmod 0755 squashfs-root/

        ARCH=x86_64 VERSION="${version}-${tag}_JB" ./appimagetool-x86_64.AppImage squashfs-root/
        pwd; ls -lah

        fileName=$(ls DisplayCAL-py3*.AppImage)
        echo "fileName: $fileName"
        md5sum "$fileName" > "${fileName}.md5"
        pwd; ls -lah

    - uses: xresloader/upload-to-github-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          file: "DisplayCAL-py3*.AppImage; DisplayCAL-py3*.zsync; DisplayCAL-py3*.md5; wxPython-*.whl; Argyll_*_bin.tgz"
          #overwrite: true
          verbose: true
          draft: false
          default_release_name: "DisplayCAL-py3 V in AppImage"
